apiVersion: apps/v1
kind: Deployment
metadata:
  name: conferencing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conferencing
  template:
    metadata:
      labels:
        app: conferencing
    spec:
      containers:
        - name: conferencing
          image: timjmiller/conferencing
          env:
            - name: ARANGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ARANGO_PASSWORD
            - name: ARANGO_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ARANGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: conferencing-service
spec:
  selector:
    app: conferencing
  ports:
    - name: conferencing
      protocol: TCP
      port: 3000
      targetPort: 3000
